spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yuan_dev
    username: yuan_dev_user
    password: 1
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true