spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yuan_dev
    username: yuan_dev_user
    password: 1
    # initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
  sql:
    init:
      platform: mysql
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#                action: create
#                create-target: yuan_database_create.sql